paths:
  input_data: "/app/data/input/"
  output_data: "/app/data/output/iot_parquet"
  jdbc_driver_path: "/app/jars/clickhouse-jdbc-0.8.4-all.jar"

spark:
  app_name: "IoTDataProcessing"
  driver_memory: "4g"
  master: "local[*]"
  adaptive_enabled: true

clickhouse:
  host: "clickhouse-server"
  port: 8123
  user: "spark_user"
  db: "default"
  table: "iot_data"